openapi: 3.0.0
info:
  title: Knowledge Base Setup and Status API endpoints
  version: '2023-10-31'
paths:
  /api/security_ai_assistant/knowledge_base:
    post:
      x-codegen-enabled: true
      x-labels: [ess, serverless]
      operationId: KnowledgeBaseSetup
      summary: Setup the Knowledge Base
      description: Setup the Knowledge Base
      tags:
        - Knowledge Base API
      parameters:
        - name: modelId
          in: query
          description: |
            (Deprecated) ELSER modelId to use when setting up the Knowledge Base. Use `inferenceId` instead. If not provided, a default model will be used.
          required: false
          schema:
            type: string
          example: "elser-model-001"
          deprecated: true
        - name: inferenceId
          in: query
          description: Inference ID to use when setting up the Knowledge Base. If not provided, a default will be used.
          required: false
          schema:
            type: string
          example: ".elser-2-elasticsearch"
        - name: ignoreSecurityLabs
          in: query
          description: Indicates whether we should or should not install Security Labs docs when setting up the Knowledge Base. Defaults to `false`.
          required: false
          schema:
            type: boolean
            default: false
          example: true
      responses:
        200:
          description: Indicates a successful call.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KnowledgeBaseResponse'
        400:
          description: Generic Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    description: The HTTP status code of the error.
                    example: 400
                  error:
                    type: string
                    description: A short description of the error.
                    example: "Bad Request"
                  message:
                    type: string
                    description: A detailed error message.
                    example: "Invalid resource ID provided."
    get:
      x-codegen-enabled: true
      x-labels: [ess, serverless]
      operationId: KnowledgeBaseStatus
      description: Get the status of the Knowledge Base
      summary: Get the status of the Knowledge Base
      tags:
        - KnowledgeBase API
      responses:
        200:
          description: Indicates a successful call.
          content:
            application/json:
              schema:
                type: object
                properties:
                  elser_exists:
                    type: boolean
                    description: (Deprecated) Indicates if the ELSER model exists for the Knowledge Base. See inference_endpoint_exists instead.
                    example: true
                    deprecated: true
                  inference_endpoint_exists:
                    type: boolean
                    description: Indicates if the Inference Endpoint is available for the Knowledge Base.
                    example: true
                  is_setup_available:
                    type: boolean
                    description: Indicates if the setup process is available for the Knowledge Base.
                    example: true
                  is_setup_in_progress:
                    type: boolean
                    description: Indicates if the setup process is currently in progress.
                    example: false
                  security_labs_exists:
                    type: boolean
                    description: Indicates if Security Labs documentation exists in the Knowledge Base.
                    example: true
                  user_data_exists:
                    type: boolean
                    description: Indicates if user data exists in the Knowledge Base.
                    example: false
                  product_documentation_status:
                    type: string
                    description: The status of the product documentation in the Knowledge Base.
                    example: "complete"
        400:
          description: Generic Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: number
                    description: The HTTP status code of the error.
                    example: 400
                  error:
                    type: string
                    description: A short description of the error.
                    example: "Bad Request"
                  message:
                    type: string
                    description: A detailed error message.
                    example: "Invalid resource ID provided."

components:
  schemas:
    KnowledgeBaseResponse:
      type: object
      description: AI assistant KnowledgeBase.
      properties:
        success:
          type: boolean
          description: Identify the success of the method execution.
          example: true
